export const CURRENCIES = [
  { code: 'USD', symbol: '$',    name: 'US Dollar' },
  { code: 'EUR', symbol: '€',    name: 'Euro' },
  { code: 'GBP', symbol: '£',    name: 'British Pound' },
  { code: 'CAD', symbol: 'CA$',  name: 'Canadian Dollar' },
  { code: 'AUD', symbol: 'A$',   name: 'Australian Dollar' },
  { code: 'NZD', symbol: 'NZ$',  name: 'New Zealand Dollar' },
  { code: 'CHF', symbol: 'CHF',  name: 'Swiss Franc' },
  { code: 'SEK', symbol: 'kr',   name: 'Swedish Krona' },
  { code: 'NOK', symbol: 'kr',   name: 'Norwegian Krone' },
  { code: 'DKK', symbol: 'kr',   name: 'Danish Krone' },
  { code: 'JPY', symbol: '¥',    name: 'Japanese Yen' },
  { code: 'CNY', symbol: '¥',    name: 'Chinese Yuan' },
  { code: 'HKD', symbol: 'HK$',  name: 'Hong Kong Dollar' },
  { code: 'SGD', symbol: 'S$',   name: 'Singapore Dollar' },
  { code: 'KRW', symbol: '₩',    name: 'South Korean Won' },
  { code: 'INR', symbol: '₹',    name: 'Indian Rupee' },
  { code: 'PHP', symbol: '₱',    name: 'Philippine Peso' },
  { code: 'IDR', symbol: 'Rp',   name: 'Indonesian Rupiah' },
  { code: 'MYR', symbol: 'RM',   name: 'Malaysian Ringgit' },
  { code: 'THB', symbol: '฿',    name: 'Thai Baht' },
  { code: 'MXN', symbol: 'MX$',  name: 'Mexican Peso' },
  { code: 'BRL', symbol: 'R$',   name: 'Brazilian Real' },
  { code: 'ZAR', symbol: 'R',    name: 'South African Rand' },
  { code: 'AED', symbol: 'د.إ',  name: 'UAE Dirham' },
  { code: 'SAR', symbol: '﷼',    name: 'Saudi Riyal' },
]

export const CALLING_CODES = [
  { code: '+1',   flag: '🇺🇸', label: '+1   (US / CA)' },
  { code: '+44',  flag: '🇬🇧', label: '+44  (UK)' },
  { code: '+61',  flag: '🇦🇺', label: '+61  (AU)' },
  { code: '+64',  flag: '🇳🇿', label: '+64  (NZ)' },
  { code: '+353', flag: '🇮🇪', label: '+353 (IE)' },
  { code: '+33',  flag: '🇫🇷', label: '+33  (FR)' },
  { code: '+49',  flag: '🇩🇪', label: '+49  (DE)' },
  { code: '+39',  flag: '🇮🇹', label: '+39  (IT)' },
  { code: '+34',  flag: '🇪🇸', label: '+34  (ES)' },
  { code: '+31',  flag: '🇳🇱', label: '+31  (NL)' },
  { code: '+46',  flag: '🇸🇪', label: '+46  (SE)' },
  { code: '+47',  flag: '🇳🇴', label: '+47  (NO)' },
  { code: '+45',  flag: '🇩🇰', label: '+45  (DK)' },
  { code: '+41',  flag: '🇨🇭', label: '+41  (CH)' },
  { code: '+7',   flag: '🇷🇺', label: '+7   (RU)' },
  { code: '+81',  flag: '🇯🇵', label: '+81  (JP)' },
  { code: '+86',  flag: '🇨🇳', label: '+86  (CN)' },
  { code: '+852', flag: '🇭🇰', label: '+852 (HK)' },
  { code: '+65',  flag: '🇸🇬', label: '+65  (SG)' },
  { code: '+82',  flag: '🇰🇷', label: '+82  (KR)' },
  { code: '+91',  flag: '🇮🇳', label: '+91  (IN)' },
  { code: '+63',  flag: '🇵🇭', label: '+63  (PH)' },
  { code: '+62',  flag: '🇮🇩', label: '+62  (ID)' },
  { code: '+60',  flag: '🇲🇾', label: '+60  (MY)' },
  { code: '+66',  flag: '🇹🇭', label: '+66  (TH)' },
  { code: '+55',  flag: '🇧🇷', label: '+55  (BR)' },
  { code: '+52',  flag: '🇲🇽', label: '+52  (MX)' },
  { code: '+27',  flag: '🇿🇦', label: '+27  (ZA)' },
  { code: '+971', flag: '🇦🇪', label: '+971 (AE)' },
  { code: '+966', flag: '🇸🇦', label: '+966 (SA)' },
]
